### ISSUE TITLE
JObject/JArray map to string

### ISSUE THREAD

**Issue by NanFengCheong** [agileobjects/AgileMapper#153]
Hi,
Is it possible configure the mapping type from JObject/JArray to string?

**Comment by SteveWilkes** [comment]
The mapper will default to calling `ToString()` on a complex type object to map it to a string, but I actually uncovered a bug when testing `JObject`; the mapper understands dictionaries, so it treats `JObject` as an `IDictionary<string, JToken>`, and is failing finding the `ToString` method on the interface. This is fixed in the latest 1.5 release code, and I'll release a new preview version soon.

Thanks for the question!

**Comment by SteveWilkes** [comment]
The bug is fixed as of v1.5-preview3, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper) - you should just be able to map a JObject member to a string, and it'll use JObject.ToString() to get the value.

Was there other configuration you wanted to do?

**Comment by NanFengCheong** [comment]
Yup.
Is it possible to configure when encounter mapping from type string -> JObject/JArray use JsonConvert.SerializeObject?

**Comment by SteveWilkes** [comment]
Give this a try:

```C#
Mapper.WhenMapping
    .From<string>().To<JObject>()
    .Map(ctx => JsonConvert.SerializeObject(ctx.Source)).ToTarget();
```

Let me know how it goes! :)
