### ISSUE TITLE
DateTime And OneOfValue Issue?

### ISSUE THREAD

**Issue by kathrin82** [agileobjects/AgileMapper#166]
We are using your AgileMapper to map between C#.Net and protobuf 3.0. Sometimes the objects are complex, with nested structure, enums, ect. 

We are currently running into an issue where we do not know how to proceed. Unfortunately, the structure is not that simple and as we do not know exactly where the problem occurs we can not narrow it further down for easier understanding. But perhaps you have an idea which can help us?

It seems to be related to the mapping from DateTime (C#) to Timestamp (protobuf) in connection with a OneOfValue Enum structure (protobuf). I generated the following Fiddle where the exception is reproduced: https://dotnetfiddle.net/q9ro9u

**Comment by SteveWilkes** [comment]
Thanks for the report and fiddle - this turned out to be a bug where the mapping from `src.Container.Params.CollectionCollection.ValueList.Definition.Default` was affecting how the mapping from `src.Container.Tasks` was being performed. It's fixed in the latest 1.6 branch code - release to follow.

Thanks again!

Steve

**Comment by SteveWilkes** [comment]
This is fixed as of v1.6-preview4, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper). Thanks again!

**Comment by SteveWilkes** [comment]
The fix for this is included in v1.6, which is now available [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper/1.6.0).

Thanks again for the feedback!
