### ISSUE TITLE
Mapping failed where type is JsonElement

### ISSUE THREAD

**Issue by NanFengCheong** [agileobjects/AgileMapper#191]
https://dotnetfiddle.net/XV18Rp

```
using System;
using System.Text.Json;
using System.Linq;
using AgileObjects.AgileMapper;

public class Program
{
	public static void Main()
	{
		string p = "[{\"a\":\"1\"}]";
		JsonElement source = JsonDocument.Parse(p).RootElement;	
		JsonElement result = Mapper.Map(source).ToANew<JsonElement>();
		Console.WriteLine("Source: " + source);
		Console.WriteLine("Result: " + result);
	}
}
```

> Source: [{"a":"1"}]
> Result: 

result is undefined after mapping.

**Comment by NanFengCheong** [comment]
@SteveWilkes Steve Wilkes can you help to look into this?

**Comment by SteveWilkes** [comment]
Hi!

Thanks for raising this!

Because `JsonElement` has [only readonly members](https://dotnetfiddle.net/tGYSOO), the mapper can create one, but can't populate it.

Fortunately, `JsonElement` has a [`Clone`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.clone?view=netcore-3.1#System_Text_Json_JsonElement_Clone) method you can use to create instances, and you can configure the mapper to use it [like this](https://dotnetfiddle.net/tGYSOO).

Hope that helps!

All the best,

Steve
