### ISSUE TITLE
DependencyInjection

### ISSUE THREAD

**Issue by fleed** [agileobjects/AgileMapper#60]
Hi

Are there extensions to configure the `IMapper` as part of `Microsoft.Extensions.DependencyInjection` (`IServiceCollection`)?

**Comment by SteveWilkes** [comment]
In the simplest case, you can make an `IMapper` instance available via dependency injection with:

```C#
services.AddSingleton(Mapper.CreateNew());
```

Because AgileMapper doesn't require up-front registrations, doesn't use anything like AutoMapper's [Profiles](http://docs.automapper.org/en/stable/Configuration.html#profile-instances), and has a first-class [inline configuration](/agileobjects/AgileMapper/wiki/Inline-Configuration) API, there's not necessarily anything to 'discover' and register at app startup. If a user chooses up-front mapper caching and / or centralised configuration (as opposed to [inline](/agileobjects/AgileMapper/wiki/Inline-Configuration)), I could see a case for a package with a service collection extension method which found and invoked that code, but it wouldn't be doing much. I'm completely open to it though, depending on feedback.
