### ISSUE TITLE
Could not load file or assembly 'AgileObjects.NetStandardPolyfills, Version=0.1.2.0, Culture=neutral, PublicKeyToken=06131ac1c008ad4e' or one of its dependencies. The system cannot find the file specified. 

### ISSUE THREAD

**Issue by mpaine-act** [agileobjects/AgileMapper#7]
My team is occasionally seeing this error message when compiling and running our MVC 5 website, which uses AgileMapper (which is a great tool).

I have found two solutions, neither of which address the issue:

1. Copy the solution's packages\AgileObjects.NetStandardPolyfills.0.1.2\lib\net40\AgileObjects.NetStandardPolyfills.dll and packages\AgileObjects.ReadableExpressions.1.8.2\lib\net40\AgileObjects.ReadableExpressions.dll to the website's bin directory. 

2. Delete the website's bin and obj directory, then recompile.  Note, this doesn't always work.

I was going to create a gulp script to copy these, as a work-around, but don't know this is a known problem or a better solution exists.

**Comment by SteveWilkes** [comment]
Thanks for the report - I'll check it out over the weekend.

Glad you're finding the mapper useful! :)

**Comment by SteveWilkes** [comment]
It sounds like the issue is the polyfills assembly not being copied into the output directory on build - if you're using a csproj does the NetStandardPolyfills reference have Copy Local set to True in its properties?

This isn't a known issue and the mapper's dependencies are configured in the standard way as far as I'm aware - they've been pulled into your project so that all seems to be ok.

**Comment by mpaine-act** [comment]
Thank you.  You gave me a good clue.  I ended up editing the .csproj file and set Private to False for those assemblies:

<Reference Include="[...]">
  **<Private>False</Private>**
  [...]
</Reference>

**Comment by SteveWilkes** [comment]
Great! Happy to help :)
