### ISSUE TITLE
i know this project is very good project,how about let the api more beautiful and easy?

### ISSUE THREAD

**Issue by sgf** [agileobjects/AgileMapper#72]
if only performance,this project is the best project .
but its API is not very easy and friend.
how about let the API more good like TinyMapper.

**Comment by SteveWilkes** [comment]
Hi!

Could you give me an example of TinyMapper's API which you prefer?

The AgileMapper API is designed to form English sentences - using an example from [TinyMapper's readme](https://github.com/TinyMapper/TinyMapper#getting-started), I personally think this:

```C#
TinyMapper.Bind<Person, PersonDto>(cfg =>
{
    cfg.Ignore(p => p.Id);
    cfg.Ignore(p => p.Email);
    cfg.Bind(p => p.LastName, dto => dto.Surname);
    cfg.Bind(target => source.Emails, typeof(List<string>));
});
```

...is less friendly than this:

```C#
Mapper.WhenMapping
    .From<Person>()
    .To<PersonDto>()
    .Map((p, dto) => p.LastName).To(dto => dto.Surname)
    .And.Ignore(dto => dto.Id, dto => dto.Email);
```

...and even *less* friendly than the inline version:

```C#
Mapper.Map(person).ToANew<PersonDto>(cfg => cfg
    .Map((p, dto) => p.LastName).To(dto => dto.Surname)
    .And.Ignore(dto => dto.Id, dto => dto.Email));
```

Also, in AgileMapper:

- You ignore *target* members, not source ones - this makes more sense to me because you're configuring the mapping of a *target*

- Enumerable target types are figured out by the mapper so don't need to be configured

- You don't *need* to perform a 'bind' setup step at all - mapping plans are figured out as and when necessary and can very effectively be [configured inline](/agileobjects/AgileMapper/wiki/Inline-Configuration)

**Comment by sgf** [comment]
if Mapper.Map<CustomerDto>(customer); 
maybe is better than?
Mapper.Map(customer).ToANew<CustomerDto>();

if by extensions method maybe is better?
customer.Map<CustomerDto>();
Zero Config is a  Very nice feature

i know AgileMapper is more Semantic
But the call chain is longer .
@SteveWilkes

**Comment by SteveWilkes** [comment]
Just to note, v1 included a short-hand source-to-target member configuration:

```cs
Mapper.WhenMapping
    .From<Person>().To<PersonDto>()
    .Map(p => p.LastName, dto => dto.Surname)
    .And.Ignore(dto => dto.Id, dto => dto.Email);
```
