### ISSUE TITLE
Recursive mapping

### ISSUE THREAD

**Issue by burakuytun-rightsoft** [agileobjects/AgileMapper#85]
Hi, 

Recursive mapping takes too much time (for my scenario) and I need to set depth for the mappings. My mapper helpers looks like this:

 public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)
  {
        return AgileObjects.AgileMapper.Mapper.Map(source).OnTo(destination);
  }

Any help would be appreciated.

Thanks.

**Comment by YandyZaldivar** [comment]
I haven't tested yet but there were optimizations on this regards in the latest version (0.26), if you haven't updated take a look:
https://github.com/agileobjects/AgileMapper/releases/tag/0.26

**Comment by burakuytun-rightsoft** [comment]
I tried it with this version

**Comment by YandyZaldivar** [comment]
I did a quick test #86, though the improvements from 0.25 to 0.26 were noticeable for my scenario.
BTW, you closed this thread.

**Comment by SteveWilkes** [comment]
Hi,

Thanks for the report - for me to properly take a look at what's happening, please could you add the definitions for the classes you're using to this issue.

And just to clarify - .OnTo() performs a [Merge mapping](/agileobjects/AgileMapper/wiki/Performing-Merges) rather than an update (that's [.Over()](/agileobjects/AgileMapper/wiki/Performing-Updates)) - was that your intention?

Cheers,

Steve
