### ISSUE TITLE
Mapping Issue - Maybe

### ISSUE THREAD

**Issue by gbansk** [agileobjects/AgileMapper#90]
I have a class that has a property of type object, when i map this property to a dto, that property doe not get evaluated or set. Its value remains null.

If i use `.After.MappingEnds.Call(d => d.Target.Status = d.Source.Status)` it maps correctly. 
If i use `.Map(ctx => ctx.Source.Status).To(vm => vm.Status)` this does not work.

```    
    public class Status
    {
        public enum StatusId
        {
            [Display(Name = "Unsubmitted")] Unsubmitted = 1,

            [Display(Name = "Approved")] Approved = 2,

            [Display(Name = "Withdrawn")] Withdrawn = 3

        }

        private Status(StatusId id,
            string name
            )
        {
            Id = id;
            Name = name;
        }

        public StatusId Id { get; }
        public string Name { get; }

        public static readonly Status Unsubmitted = new Status(StatusId.Unsubmitted, "Unsubmitted");
        public static readonly Status Approved = new Status(StatusId.Approved, "Approved");
        public static readonly Status Withdrawn = new Status(StatusId.Withdrawn, "Withdrawn");

        public static Status GetStatus(StatusId statusId)
        {
            switch (statusId)
            {
                case StatusId.Unsubmitted:
                    return Unsubmitted;
                case StatusId.Approved:
                    return Approved;
                case StatusId.Withdrawn:
                    return Withdrawn;
                default:
                    throw new InvalidOperationException();
            }
        }

    }

    public class Parent
    {
        public Status.StatusId ParentStatusId { get; set; }
        public Status ParentStatus => Status.GetStatus(ParentStatusId);
    }

    public class ParentDto
    {
        public Status.StatusId ParentStatusId { get; set; }
        public Status ParentStatus { get; set; }
    }

    public class ParentMappingConfiguration : MapperConfiguration
    {
        protected override void Configure()
        {
            WhenMapping
                .From<Parent>()
                .To<ParentDto>()
                .Map(ctx => ctx.Source.ParentStatus).To(dto => dto.ParentStatus);
            
            GetPlansFor<Parent>().To<ParentDto>();
        }
    }

    public interface IDtoMapper<in TSource, out TDest>
    {
        TDest Map(TSource source);
    }

    public class ParentMapper : IDtoMapper<Parent, ParentDto>
    {
        private readonly IMapper _mapper;

        public ParentMapper()
        {
            _mapper = Mapper.CreateNew();
            _mapper.WhenMapping.UseConfigurations
                .From<ParentMappingConfiguration>()
                .From<ChildMappingConfiguration>();
        }

        public ParentDto Map(Parent parent)
        {
            return _mapper.Map(parent).ToANew<ParentDto>();
        }
    }

    public class UnitTest1
    {
        [Fact]
        public void PropertyIsObject()
        {
            var parent = new Parent {ParentStatusId = Status.StatusId.Unsubmitted};

            var map = new ParentMapper().Map(parent);

            Assert.Equal(map.ParentStatusId, parent.ParentStatusId);
            Assert.Equal(map.ParentStatus, parent.ParentStatus);
        }
    }

```
ParentStatusId is correctly mapped, but ParentStatus is null.
Am I missing something, or do i have the mapping wrong.

Thanks,
Gary

**Comment by SteveWilkes** [comment]
Hi Gary!

There's definitely an issue to investigate here - it doesn't map because `Status` has a private constructor and a factory method with no settable members, but the source and target members match so it should work without configuration.

I'll sort it out and get back to you. Thanks for the feedback! :)

Steve

**Comment by SteveWilkes** [comment]
This is actually slightly more nuanced than I thought - `Status` isn't being mapped because the mapper can't create an instance of it and it has no settable properties, so there's no point checking if it's already populated. It doesn't assign the source `Status` because it wants to create a *copy* of the object, not reuse the same instance.

I'll sort this out in the next release by making sure the following configuration is obeyed:

```C#
WhenMapping
    .From<Parent>().To<ParentDto>()
    .CreateInstancesOf<Status>()
    .Using((p, dto) => Status.GetStatus(p.ParentStatusId));
```

In the following release I'll extend object creation to include discoverable, callable factory methods; if the type has:

- A static method
- Returning that type
- With a name starting with 'Get' or 'Create'
- With all-populable parameters (like in this case, `Parent` would need a property named `StatusId` to map to the `Status.GetStatus()` `statusId` parameter)

...it'll be wired in and used for object creation.

**Comment by SteveWilkes** [comment]
Actually it looks like the `CreateInstancesOf` configuration works! I've written [a Fiddle](https://dotnetfiddle.net/Aj9V1s) and it looks fine.

I'll still add the factory method support, though :)

**Comment by SteveWilkes** [comment]
Just to mentioned I've just merged the automagic factory method support into master - release to follow :)

**Comment by SteveWilkes** [comment]
Automatic factory method use added in [v0.28](https://www.nuget.org/packages/AgileObjects.AgileMapper) :)
